[customizations.installer.kickstart]
contents = """
text --non-interactive
zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --noswap --type=btrfs
#ignoredisk --only-use=nvme0n1
network --bootproto=dhcp --device=link --activate --onboot=on
user --name=cappy --groups=wheel --iscrypted --password='$y$j9T$NlhgMqx2O9Ej0g7esW/3W/$WMWyra7vEgfXg6ox5iNbvZHuLJShv95funlzthGPu7/'
rootpw --iscrypted '$y$j9T$NlhgMqx2O9Ej0g7esW/3W/$WMWyra7vEgfXg6ox5iNbvZHuLJShv95funlzthGPu7/'
user --name=aikoyori --groups=wheel
user --name=eri --groups=wheel
sshkey --username=cappy "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINBx7F+TYn/bjOA2nubAi5JaoAlzoMfIx3rvP4k5iOmA cappy@fyralabs.com"
sshkey --username=root "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINBx7F+TYn/bjOA2nubAi5JaoAlzoMfIx3rvP4k5iOmA cappy@fyralabs.com"
%post
bootc switch --mutate-in-place --transport registry ghcr.io/korewachino/ucore-cappy:latest
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Runtime"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription",
]
